{{ range $projectName,$project := .Values.projects }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $projectName }}
  # application needs to be installed after the crds
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
   project: {{ $projectName }}
   revisionHistoryLimit: 3
   syncPolicy:
     automated:
       prune: true
       selfHeal: true
       allowEmpty: true
     syncOptions:
       - CreateNamespace=true
   destination:
     server: https://kubernetes.default.svc
     namespace: {{ $.Release.Namespace }}
   source:
     path: {{ $project.git.path | default $projectName }}
     repoURL: {{ $project.git.repoURL }}
     targetRevision: {{ $project.git.branch | default "main" }}
     helm:
       values: |
         values:
           {{- $project.values | toYaml | nindent 12}}
       valueFiles:
         - values.yaml
         {{- if ($project.values).stage }}
         - values-{{ $project.values.stage }}.yaml
         {{- end}}
---
{{- end }}